# This simply documents the versions of Node.js and npm installed, along with
# the versions of the linked library availble to the runtime. This provides
# an audit trail for buggy builds
RUN node -v
RUN node -p "process.versions"
RUN npm --version
