name: Check generated TOCs

on:
  pull_request:
    paths:
      - README.md
      - CONTRIBUTING.md
      - docs/BestPractices.md
      - .github/workflows/doctoc.yml
      - 'package*.json'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  doctoc:
    name: Doc TOC Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run doctoc
        run: npm run format:toc:check
